In [98]:
import numpy as np
import pandas as pd
from numpy import pi
from numpy import newaxis

In [55]:
a = np.arange(15).reshape(3, 5)
a3 = np.arange(24).reshape(2,3,4)# 3d array
b = np.array([6, 7, 8])
c = np.array([(1.5,2,3), (4,5,6)])
d = np.array( [ [1,2], [3,4] ], dtype=complex )
zero = np.zeros( (3,4) )
ones = np.ones( (2,3,4), dtype=np.int16 )
random = np.random.random((2,3))
random1 = np.floor(10*np.random.random((3,4))) # 0 to 10 random number
empty = np.empty( (2,3) )
step = np.arange( 10, 30, 5 )#start end step
stepFloat = np.arange( 0, 2, 0.3 ) 
fix = np.linspace( 0, 2, 9 )#start end size


x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)

In [34]:
print("shape is {}".format(a.shape))
print(a.ndim)
print(a.dtype.name)
print("item size is {}".format(a.itemsize))
print("size: {}".format(a.size))
print("type is: {}".format(d.dtype))
fix
f

shape is (3, 5)
2
int64
item size is 8
size: 15
type is: complex128


array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [42]:
#Basic Operations
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a-b
b**2
a*b
10*np.sin(a)
a<35

array([ True,  True, False, False], dtype=bool)

In [102]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print("elementwise product:\n{}".format(A * B))                       # elementwise product
print("matrix product:\n{}".format(A @ B))                      # matrix product
print("matrix product:\n{}".format(A.dot(B)))                      # another matrix product
print("Cross product:\n{}".format(np.cross(A,B))) 

elementwise product:
[[2 0]
 [0 4]]
matrix product:
[[5 4]
 [3 4]]
matrix product:
[[5 4]
 [3 4]]
Cross product:
[-2 -3]


In [61]:
a = np.random.random((2,3))
a.sum()
a.min()
a.max()
np.exp(a*1j)

array([[ 0.88731714+0.46115972j,  0.82836810+0.56018415j,
         0.98868964+0.14997596j],
       [ 0.99992176+0.01250924j,  0.61229001+0.79063325j,
         0.98310911+0.18302045j]])

In [70]:
b = np.arange(12).reshape(3,4)
print(b)
b.sum(axis = 1) #axis = 0 means column, axis = 1 means row
b.min(axis=1)
b.cumsum(axis=0) # cumulative sum along each row

a = np.arange(12) #1D array
a.cumsum()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [76]:
#Universal Functions
#all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, 
#ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, 
#inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, 
#outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where
B = np.arange(3)
np.exp(B)
np.sqrt(B)
C = np.array([2., -1., 4.])
np.add(B, C)

array([ 2.,  0.,  6.])

In [89]:
#Indexing, Slicing and Iterating
a = np.arange(10)**3
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)
print(a[ : :-1])                                 # reversed a
print(a)

[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[-1000     1 -1000    27 -1000   125   216   343   512   729]


In [95]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int) #f(x,y) x and y are index, f(1,1) means cell 1,1
print(b)
print(b.T)  # returns the array, transposed
print(b.ravel())  # returns the array, flattened
b.resize((2,6))#The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]]
[ 0  1  2  3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43]


In [100]:
#Stacking together different arrays
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.column_stack((a,b)))
print(np.row_stack((a,b)))

[[ 3.  3.]
 [ 9.  0.]
 [ 8.  3.]
 [ 6.  2.]]
[[ 3.  3.  8.  3.]
 [ 9.  0.  6.  2.]]
[[ 3.  3.  8.  3.]
 [ 9.  0.  6.  2.]]
[[ 3.  3.]
 [ 9.  0.]
 [ 8.  3.]
 [ 6.  2.]]
